### PR TITLE
Hugo theme update to fix IE JS

### PR DESCRIPTION
**Pull request by autumnfound**
Signed-off-by: Martin Lowe <martin.lowe@eclipse-foundation.org>

### CODE REVIEW

**Comment by flora8984461** [comment]
Is there a preview for openmobility.eclipse.org ?

**Comment by flora8984461** [comment]
It is good.

Although the tweets not showing, not a problem, there is a link and the IE is forwarding me to use Edge. Everything is good!

image
image

**Review by flora8984461 — APPROVED** [review]

**Review by ericpoirier — APPROVED** [review]

**Comment by chrisguindon** [comment]
@flora8984461 Please open a separate issue for that!

**Comment by flora8984461** [comment]
> @flora8984461 Please open a separate issue for that!

I think this would be okay. Since on IE there is a link to the twitter, and it is windows itself redirect you to use Edge. I think it should not be a problem?

**Comment by chrisguindon** [comment]
@flora8984461 We create these types of issues to have those discussions! It's possible that we decide that this is good enough but that's outside of the scope of this issue.

**Comment by flora8984461** [comment]
> @flora8984461 We create these types of issues to have those discussions! It's possible that we decide that this is good enough but that's outside of the scope of this issue.

Sounds good, opened issue #31

**Pull request merged**
