### PR TITLE
prepare website for production

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Comment by angelobanse** [comment]
It seems that everything went well. :thumbsup:

How do the updates to the website work? Is it done automatically with every commit or should we make a pull request each time?

**Comment by angelobanse** [comment]
> It seems that everything went well. 👍
> 
> How do the updates to the website work? Is it done automatically with every commit or should we make a pull request each time?

I just saw the changes to the Travis script.

**Comment by chrisguindon** [comment]
Hi @angelobanse,

The website is currently hosted on our forges virtual machine and we currently have a cron job that will pull in changes every 5 minutes.

I am currently waiting testing this process to make sure that every works.

**Comment by chrisguindon** [comment]
The website is now ready:
https://openmobility.eclipse.org/

We needed to make some changes to our reverse-proxy to make sure that expire the cache for a page after 5 minutes.

Please let me know if you push a change to the website and you don't see it deployed within 10 minutes (5 min for the the cron job + 5 minutes for the cache to expire).

**Comment by angelobanse** [comment]
Great!

**Comment by angelobanse** [comment]
Hi @chrisguindon,

I commited some minor changes (https://github.com/EclipseFdn/openmobility.eclipse.org/commit/520a5fdc2efe44435587b28aedf4e949778b5adc) mainly to test the automatic deployment, but after some hours i can't see those changes in the website (i have deleted my cache, etc.).

Could you check if there is an issue on the server-side? Supposedly everything went well at the deployment (https://github.com/EclipseFdn/openmobility.eclipse.org/deployments).

Should i sign-off every commit?

thanks as always, and sorry to bother you so much :pray:

**Comment by chrisguindon** [comment]
+1 Verified!

I took a look and we are experiencing a permission issue with the cron job that pull-ins new changes for the website.

@eclipsewebmaster is currently working to address this issue! We will keep you posted!

Regarding the sign-off:

You should include the sign-off-by footer for all your commits but this is not causing the problem.

...and do not worry, we are here to support the website! You are not a bother!

Cheers,

**Comment by eclipsewebmaster** [comment]
The automated checkout should now be working as expected.

**Comment by angelobanse** [comment]
Hi @eclipsewebmaster, 
it's weird, but the changes we do **still do not appear automatically** on the website.

Can you guys check it out?

It is important for the website to be updated automatically with each commit that we make, since we will be working a lot on it tomorrow and this weekend (the site will be "officially" launched here on Monday).

Thx! :grinning:

**Comment by chrisguindon** [comment]
Hi @angelbanse,

I am on vacation today but I sent a message asking @eclipsewebmaster to take a look at this!

**Pull request merged**
